server:
  port: 8080

spring:
  application:
    name: gestion-productos
  datasource:
    url: jdbc:postgresql://ep-red-water-are1utxf-pooler.c-4.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_Ai0bzPjJu7Ca
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.hibernate.SQL: info
